export const api_key = '0a1f6aa2a25c4c0591434124240407'

export const weatherImages = {
    'Patchy rain nearby':require('../assets/patchy-rain.png'),
    'Moderate rain':require('../assets/patchy-rain.png'),
    'Sunny':require('../assets/sunny.png'),
    'Clear':require('../assets/sunny.png'),
    'Overcast':require('../assets/cloudy-sun.png'),
    'Cloudy':require('../assets/cloudy.png'),
    'Cloudy ':require('../assets/cloudy.png'),
    'Light rain':require('../assets/patchy-rain.png'),
    'Light drizzle': require('../assets/patchy-rain.png'),
    'Moderate or heavy rain with thunder':require('../assets/thunderstorm.png'),
    'Thunderstorm':require('../assets/thunderstorm.png'),
    'Thundery outbreaks possible':require('../assets/thunderstorm.png'),
    'Thundery outbreaks possible ':require('../assets/thunderstorm.png'),
    'Heavy rain at times':require('../assets/heavy-rain.png'),
    'Heavy rain':require('../assets/heavy-rain.png'),
    'Partly cloudy':require('../assets/cloudy-sun.png'),
    'Partly Cloudy':require('../assets/cloudy-sun.png'),
    'Mist':require('../assets/mist.png'),
    'Light rain shower':require('../assets/patchy-rain.png'),
    'Patchy light rain':require('../assets/patchy-rain.png'),
    'Patchy light drizzle':require('../assets/patchy-rain.png'),
    'Patchy rain possible':require('../assets/patchy-rain.png'),
    'Moderate rain at times':require('../assets/patchy-rain.png'),
    'Moderate or heavy rain shower':require('../assets/heavy-rain.png'),
    'Torrential rain shower':require('../assets/heavy-rain.png'),
    'Fog': require('../assets/fog.png'),
    'Partly Cloudy ':require('../assets/cloudy-sun.png'),
}